add support for single arrows
arx-insanity/ArxLibertatis pull request #25
Opened 2022-12-26 20:49 UTC by meszaros-lajos-gyorgy

2022-12-26 20:58 UTC, fredlllll requested changes

2022-12-26 20:58 UTC, fredlllll commented on src/core/Core.cpp
> +					if (getInventoryItemWithLowestDurability("arrow", 1.f) != nullptr) {
you could put these 2 conditions into an OR as the bodies of the blocks seem to be the same?

2022-12-26 20:58 UTC, fredlllll commented on src/core/Core.cpp
> +				// if(eeMousePressed1() && getInventoryItemWithLowestDurability("arrows", 1.f) != nullptr) {
the point of source control is that you dont have to keep comments of old code around :P

2022-12-26 20:58 UTC, fredlllll commented on src/core/Core.cpp
> +				if (arrow) {
why do a comparison to nullptr further up but not here?

2022-12-26 20:58 UTC, fredlllll commented on src/core/Core.cpp
> +					if(quiver) {
also no comparison to nullptr, either dont do it at all, or do it everywhere, consistency is key :P

2022-12-26 21:05 UTC, fredlllll requested changes

2022-12-26 21:05 UTC, fredlllll commented on src/core/Core.cpp
> +				if(eeMousePressed1() && getInventoryItemWithLowestDurability("arrow", 1.f) != nullptr && getInventoryItemWithLowestDurability("arrows", 1.f) != nullptr) {
thats not what i meant

```
if(eeMousePressed1()) {
	if (getInventoryItemWithLowestDurability("arrow", 1.f) != nullptr || getInventoryItemWithLowestDurability("arrows", 1.f) != nullptr) {
		changeAnimation(io, 1, alist[ANIM_MISSILE_STRIKE_PART_1]);
		io->isHit = false;
	}
}
```

is what i meant

2022-12-26 21:05 UTC, fredlllll commented on src/core/Core.cpp
> +					if(quiver) {
you forgot to fix that one to

`if (quiver != nullptr)`

2022-12-26 21:20 UTC, fredlllll approved these changes

2022-12-27 12:15 UTC, meszaros-lajos-gyorgy commented
merged it into insanity branch manually because it contained conflicts

2022-12-27 12:15 UTC, closed without merging